// One-shot backfill: embed every reddit_posts row that lacks a vector.
//
// Why: embeddings are normally generated by the worker's `embed` job on the
// daily cron, so on a fresh deploy posts stay unembedded until the worker runs.
// This lets you populate vectors immediately after adding EMBEDDINGS_API_KEY,
// so the very first request already hits the semantic clustering path.
//
//   EMBEDDINGS_API_KEY=sk-... \
//     SUPABASE_URL=... SUPABASE_SERVICE_ROLE_KEY=... \
//     bun run scripts/embed-posts.ts
//
// Loops until no unembedded posts remain (50 per pass). No-op if no provider.
import { hasEmbeddingsProvider, embedUnembeddedPosts } from "../src/lib/ai/embeddings";
import { supabaseServer } from "../src/lib/db/supabaseClients";

async function main() {
  if (!supabaseServer()) {
    console.error("Missing SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY env vars.");
    process.exit(1);
  }
  if (!hasEmbeddingsProvider()) {
    console.error(
      "Missing EMBEDDINGS_API_KEY. Set it to embed posts (OpenAI-compatible).",
    );
    console.error("Until then, clustering runs in lexicon mode — theme_clusters still populate.");
    process.exit(1);
  }

  let pass = 0;
  let total = 0;
  // Cap passes to avoid an unbounded loop if vectors silently fail to persist.
  for (let i = 0; i < 200; i++) {
    pass++;
    const n = await embedUnembeddedPosts();
    total += n;
    console.log(`[embed-posts] pass ${pass}: embedded ${n}`);
    if (n === 0) break;
  }
  console.log(`[embed-posts] done — ${total} posts embedded over ${pass} pass(es).`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
